[package]
name = "rust-server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
fastrand = "1.9.0"
